# Generated by Django 5.0.4 on 2024-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('review', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
            ],
        ),
    ]
