# Generated by Django 5.0.4 on 2024-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
