# Generated by Django 5.0.4 on 2024-04-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customers_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
