# Generated by Django 5.0.4 on 2024-04-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_customers_photo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testinominal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("mail", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=100)),
                ("about", models.TextField()),
                ("review", models.TextField()),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="customer_photos/"
                    ),
                ),
                ("photo_url", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Customers",
            new_name="Customer",
        ),
    ]
