# Generated by Django 5.0.4 on 2024-04-15 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="query",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="mobile",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
