# Generated by Django 5.0.4 on 2024-04-15 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_query_created_at_alter_query_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
